name: OpenCADC AWS CLI Docker CI

on:
  pull_request:
  push:
  release:

jobs:
  package:
    environment: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/docker.yml
        with:
          version: '3.12'
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
          CI_REGISTRY_ORGANIZATION: ${{ secrets.CI_REGISTRY_ORGANIZATION }}
