name: OpenCADC AWS CLI Docker CI

on:
  pull_request:
  push:
  release:

jobs:
  package:
    environment: Actions
    uses: ./.github/workflows/docker.yml
    secrets:
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
      CI_REGISTRY_ORGANIZATION: ${{ secrets.CI_REGISTRY_ORGANIZATION }}
    with:
      version: '3.12'
