name: Reusable Docker workflow

env:
  # Allow the set-env command below
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      CI_REGISTRY_USER:
        required: true
      CI_REGISTRY_TOKEN:
        required: true
      CI_REGISTRY_ORGANIZATION:
        required: true

jobs:
  docker-build-publish:
    environment: docker-actions
    # github.ref == 'refs/heads/master' ||
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/${{ inputs.version }}
          push: true
          tags: ${{ secrets.CI_REGISTRY_ORGANIZATION }}/awscli:${{ inputs.version }}-slim
